### ISSUE TITLE
1. Database Creation:

### ISSUE THREAD

**Issue by krishna-iamneo** [krishna-iamneo/Job-Board-Clone#1]
**Tasks:**

1. Create a database named "job_board".
2. Create a table named "jobs" with columns for job ID (auto-incremented), job role, job description, company name, and apply link.

**Comment by krishna-iamneo** [comment]
@shivam-neo I have uploaded the code, review it as early as possible

**Comment by shivam-neo** [comment]
In database Creation as name suggest only database should be created not table so create a separate file  for table creation.

**Comment by krishna-iamneo** [comment]
ok. will update it.

**Comment by krishna-iamneo** [comment]
The creation of the database and the creation of tables have been separated and updated.

**Comment by shivam-neo** [comment]
yep its looking good
