### ISSUE TITLE
3. Main page-Applicant/Admin-Login

### ISSUE THREAD

**Issue by krishna-iamneo** [krishna-iamneo/Job-Board-Clone#2]
**Description:** Implement functionality to allow admin to log in and access admin features.

**Tasks:**

1. Prompt admin or applicant, 
        - If applicant, allow applicant to do applicant functionalities (not required now).
2. If admin, Prompt admin to enter username and password.
3. Verify username and password against hardcoded credentials.
        - If invalid credentials display appropriate message to enter valid credentials.
4. If credentials are correct, prompt admin with a **menu of functionalities** along with indices.
5. Allow admin to enter the index of the desired functionality.
       - If invalid index, display appropriate message to enter valid index.
7. Perform the corresponding function based on the entered index. (Details provided below)
8. Provide an option to exit the application from the menu.

Menu of Functionalities:

1. Create Job
2. Edit Job
3. Delete Job
4. Search Job
5. View all Jobs

Note: Create the functions alone in the code, no need to add the methods.

**Comment by krishna-iamneo** [comment]
I have uploaded the code.

**Comment by shivam-neo** [comment]
the code is proper and working of code is fine
