### ISSUE TITLE
4. Admin-Functionalities 1

### ISSUE THREAD

**Issue by krishna-iamneo** [krishna-iamneo/Job-Board-Clone#3]
**Menu of Functionalities:**
1. Create Job - (refer the database table for details).
2. Delete Job - (If this option is selected, all the job ids should be displayed and admin can Delete job by entering Job ID).

**Comment by krishna-iamneo** [comment]
Update here, after completing the task

**Comment by bharath-neo** [comment]
Uploaded the code, kindly check and update for any changes.

**Comment by shivam-neo** [comment]
The code is proper and its naming convection is okay  code is fine
