### ISSUE TITLE
5. Admin - Functionalities 2

### ISSUE THREAD

**Issue by krishna-iamneo** [krishna-iamneo/Job-Board-Clone#4]
Add the following functionalities.

**Menu of Functionalities:**
3. View Job - List all the jobs if this option is selected.
4. Search Job (search job by job id, if the option is selected).
5. Search Job by Job role (search job by job role)

**Comment by krishna-iamneo** [comment]
This should be assigned to naga sai kumar, since he is on leave, @shivam-neo will work on this.

**Comment by shivam-neo** [comment]
Done the work and also check the code its working fine
