### ISSUE TITLE
6. Applicant-Functionalites

### ISSUE THREAD

**Issue by krishna-iamneo** [krishna-iamneo/Job-Board-Clone#5]
If Applicant is prompted, then the applicant can perform the following functions:

**Note: No need login credentials for Applicant.**

Three functions that can be performed by the Applicant should be listed with indices.
1. View Jobs(Applicant can view all the jobs by choosing this option).
2. Search Job (When the Applicant chooses this option, he/she can able to search job by entering Job Role).
3. Provide an Exit option to exit from the applicant functionalities.

Note: Applicant can apply for the job by clicking the apply link.

**Comment by shivam-neo** [comment]
Done checked and verified its working fine
